### ISSUE TITLE
edges throws error

### ISSUE THREAD

**Issue by hiaw** [leighshepperson/absinthe-relay-starter-kit#1]
I got this error when trying to get the app running using just graphiql

```
[error] #PID<0.320.0> running MyApp.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /graphiql
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: 0
        (absinthe_relay) lib/absinthe/relay/connection.ex:215: Absinthe.Relay.Connection.from_list/3
        (my_app) web/schema/schema.ex:21: anonymous fn/2 in MyApp.Schema.__absinthe_type__/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:158: Absinthe.Phase.Document.Execution.Resolution.resolve_field/4
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:186: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:133: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:186: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:133: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:101: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:78: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe) lib/absinthe/pipeline.ex:201: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:148: Absinthe.Plug.execute/2
        (absinthe_plug) lib/absinthe/plug.ex:115: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:154: Phoenix.Router.Route.forward/4
        (my_app) lib/phoenix/router.ex:261: MyApp.Router.dispatch/2
        (my_app) web/router.ex:1: MyApp.Router.do_call/2
        (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.phoenix_pipeline/1
        (my_app) lib/plug/debugger.ex:123: MyApp.Endpoint."call (overridable 3)"/2
        (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/danielchong/Documents/Development/Other/Elixir/_examples/_graphql/absinthe-relay-starter-kit/my_app/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by hiaw** [comment]
using the query

```
{
  viewer {
    name 
    id
    widgets {
      edges {
        node {
          id
        }
      }
    }
  }
}
```
